export declare function DATE(year: number, month: number, day: number): number;
export declare function TIME(hour: number, minute: number, second: number): number;
export declare function DAY(date: number): number;
export declare function MONTH(date: number): number;
export declare function YEAR(date: number): number;
export declare function HOUR(date: number): number;
export declare function MINUTE(date: number): number;
export declare function SECOND(date: number): number;
export declare function NOW(): number;
export declare function DATEDIF(startN: number, endN: number, unit: string): number;
