import { cellValue } from "../types";
export declare function SUM(...rest: cellValue[]): number;
export declare function AVERAGE(...rest: cellValue[]): number;
export declare function COUNT(...rest: cellValue[]): number;
export declare function COUNTA(...rest: cellValue[]): number;
export declare function COUNTBLANK(...rest: cellValue[]): number;
export declare function MAX(...rest: cellValue[]): number;
export declare function MIN(...rest: cellValue[]): number;
export declare function PRODUCT(...rest: cellValue[]): number;
export declare function SUMPRODUCT(...sets: cellValue[][]): number;
export declare function SUMSQ(...rest: cellValue[]): number;
export declare function VARP(...rest: cellValue[]): number;
export declare function STDEVP(...rest: cellValue[]): number;
export declare function POWER(num: cellValue, pow: cellValue): number;
export declare function QUOTIENT(num: cellValue, div: cellValue): number;
export declare function SQRT(num: cellValue): number;
export declare function ABS(num: cellValue): number;
export declare function RAND(): number;
export declare function PI(): number;
export declare function INT(num: cellValue): number;
export declare function ROUND(num: cellValue, digits?: cellValue): number;
export declare function ROUNDDOWN(num: cellValue, digits: cellValue): number;
export declare function ROUNDUP(num: cellValue, digits?: cellValue): number;
export declare function TRUNC(num: cellValue): number;
export declare function EVEN(num: cellValue): number;
export declare function ODD(num: cellValue): number;
